### Buscar time
POST http://localhost:3000/time
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjI3Yjc1ZWNiLTQ3YjEtNDc4Ni1hOGE5LWYwOGUyODY2NzViOCIsIm5vbWUiOiJqb2FvIiwiaWF0IjoxNzM5OTIyNTY2LCJleHAiOjE3NDI1MTQ1NjZ9.EXAOgYo7017ayDhE1_DgkWCATrUrFg3-1hCsoVCnMgk
Content-Type: application/json

{
    "nome": "socanela24",
    "esporte_id": "f139bed9-44e9-4585-af47-2573627f760a",
    "sigla": "scl23",
    "logotipo_url": "teste",
    "dt_fundacao": "2024-12-12"

}


### Buscar time
GET http://localhost:3000/time/4e136caf-4f41-40b0-b108-4a313a042b9a

### Buscar times
GET http://localhost:3000/time

### Buscar times
DELETE http://localhost:3000/time/