### Buscar time
POST http://localhost:3000/time
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjUxMjBhMmNlLTg2YzAtNDFkYS1iMWFiLTVhYzYzOWM1NGZkNCIsIm5vbWUiOiJrZXZpbmxpbmRvIiwiaWF0IjoxNzM5NzExNTA1LCJleHAiOjE3NDIzMDM1MDV9.LVbkcBdGR1aeK_qT-LtRfe0HB5QnYALRQjVKUewl-A4
Content-Type: application/json

{
    "nome": "socanela23",
    "esporte_id": "f139bed9-44e9-4585-af47-2573627f760a",
    "sigla": "scl23",
    "logotipo_url": "teste",
    "dt_fundacao": "2024-12-12"

}


### Buscar time
GET http://localhost:3000/time/4e136caf-4f41-40b0-b108-4a313a042b9a

### Buscar times
GET http://localhost:3000/time